### ISSUE TITLE
Ctrl+S opens "save as" popup instead of toggle sidebar

### ISSUE THREAD

**Issue by HugoFerrant** [marlosoft/slack-toggle-sidebar#4]
On last public Firefox update (68.0.1 linux 64-bit), the extension's shortcut is overridden by the native CTRl+S for "save as", implying the extension can't be used anymore as there is no fallback shortcut or shortcuts settings.

**Comment by peter-lyons-kehl** [comment]
Hi John @factorin-j,

Thank you for Slack Toggler SideBar.

I confirm that Ctrl+S stopped working on Linux as Hugo described above. Firefox v. 68.0.1, but also 70 alpha - so it's their intention.

You may be interested in https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox. Chrome also has an API that is similar. Would you consider that, please?

**Comment by HugoFerrant** [comment]
this might help too : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands
